import bcrypt from 'bcryptjs';
import sequelize from '../config/database.js';
import { Role, User, Warehouse, Rental } from '../models/index.js';
import { UserRole } from '../interfaces/interfaces.js';

const seedDatabase = async () => {
    try {
        console.log('⏳ Connecting to database...');
        await sequelize.authenticate();
        console.log('✅ Database connected.');

        // 1. Ensure tables exist
        await sequelize.sync();

        console.log('⏳ Seeding Roles...');
        const roles = [
            { name: UserRole.ADMIN, description: 'Administrador del sistema LogiStock' },
            { name: UserRole.JEFE_BODEGA, description: 'Jefe encargado de gestionar una bodega' },
            { name: UserRole.AUXILIAR, description: 'Auxiliar de bodega para operaciones' },
            { name: UserRole.CLIENTE, description: 'Cliente que requiere almacenar stock' },
        ];

        for (const roleData of roles) {
            await Role.findOrCreate({
                where: { name: roleData.name },
                defaults: roleData
            });
        }
        console.log('✅ Roles created successfully.');

        console.log('⏳ Seeding Users...');
        // Default password hash
        const hashedPassword = await bcrypt.hash('cliente1234', 12);

        const adminRole = await Role.findOne({ where: { name: UserRole.ADMIN } });
        const managerRole = await Role.findOne({ where: { name: UserRole.JEFE_BODEGA } });
        const operatorRole = await Role.findOne({ where: { name: UserRole.AUXILIAR } });
        const clientRole = await Role.findOne({ where: { name: UserRole.CLIENTE } });

        const users = [
            {
                roleId: clientRole!.id,
                firstName: 'Client',
                lastName: 'Demo',
                email: 'cliente1@gmail.com',
                password: hashedPassword,
                isActive: true,
                isVerified: true,
                phone: '3001234567'
            },
            {
                roleId: adminRole!.id,
                firstName: 'Admin',
                lastName: 'Demo',
                email: 'admin1@gmail.com',
                password: hashedPassword,
                isActive: true,
                isVerified: true,
                phone: '3009876543'
            },
            {
                roleId: managerRole!.id,
                firstName: 'Manager',
                lastName: 'Warehouse',
                email: 'manager1@gmail.com',
                password: hashedPassword,
                isActive: true,
                isVerified: true,
                phone: '3001112233'
            },
            {
                roleId: operatorRole!.id,
                firstName: 'Assistant',
                lastName: 'Operator',
                email: 'operator1@gmail.com',
                password: hashedPassword,
                isActive: true,
                isVerified: true,
                phone: '3004445566'
            }
        ];

        for (const userData of users) {
            const [user, created] = await User.findOrCreate({
                where: { email: userData.email },
                defaults: userData
            });
            if (created) {
                console.log(`- User ${userData.email} (Role: ${userData.roleId}) created.`);
            }
        }
        console.log('✅ Users created successfully.');

        console.log('⏳ Seeding Warehouses...');
        const warehouseSeedData = [
            {
                name: 'LogiStock Norte A-01',
                description: 'Bodega de uso general en zona industrial norte. Piso de concreto reforzado, doble puerta de furgón, iluminación LED completa. Ideal para distribución masiva de bienes secos (textiles, calzado, papelería, electrodomésticos). Sin restricciones de temperatura. Capacidad de rack hasta 6 m.',
                warehouseType: 'GENERAL',
                city: 'Medellín',
                address: 'Calle 80 #30-15, Zona Industrial Norte',
                postalCode: '050001',
                storageLength: 40,
                storageWidth: 30,
                storageHeight: 8,
                usableArea: 1100,
                utilitiesIncluded: true,
                utilitiesResponsible: 'ARRENDADOR',
                utilitiesDetails: 'Agua, Energía eléctrica, Aseo',
                hasSecuritySystem: true,
                hasLoadingDock: true,
                hasParking: true,
                accessHours: '24/7',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8ed7c83a7f?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 4800000,
                capacityOccupied: 35,
            },
            {
                name: 'LogiStock Frío B-02',
                description: 'Cuarto frío de alta capacidad para almacenamiento de alimentos perecederos, lácteos, carnes y productos farmacéuticos. Temperatura controlada entre 0°C y 8°C con sistema de respaldo de emergencia. Certificación INVIMA. Paredes de panel tipo sándwich. Acceso con antecámara termobuffer.',
                warehouseType: 'REFRIGERADA',
                city: 'Bogotá',
                address: 'Av. Boyacá #12A-50, Zona Franca Bogotá',
                postalCode: '110231',
                storageLength: 25,
                storageWidth: 20,
                storageHeight: 5,
                usableArea: 450,
                utilitiesIncluded: false,
                utilitiesResponsible: 'ARRENDATARIO',
                utilitiesDetails: 'El arrendatario paga Energía eléctrica (consumo refrigeración) y Agua directamente',
                hasSecuritySystem: true,
                hasLoadingDock: true,
                hasParking: true,
                accessHours: 'Lun–Sáb 5:00 AM – 10:00 PM',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 7200000,
                capacityOccupied: 60,
            },
            {
                name: 'LogiStock Delicados C-03',
                description: 'Espacio acondicionado para mercancía frágil, artículos de alto valor y componentes electrónicos. Piso antiestático, control de humedad relativa (40–60%), sistema UPS para cortes de luz. Vigilancia privada 24/7. Prohibido ingreso con calzado metálico. Acceso con escáner de ingreso.',
                warehouseType: 'DELICADOS',
                city: 'Medellín',
                address: 'Carrera 48 #18-20, Piso 1, Edificio LogiPark',
                postalCode: '050024',
                storageLength: 20,
                storageWidth: 15,
                storageHeight: 4,
                usableArea: 270,
                utilitiesIncluded: true,
                utilitiesResponsible: 'ARRENDADOR',
                utilitiesDetails: 'Agua, Energía eléctrica, UPS, Clima artificial',
                hasSecuritySystem: true,
                hasLoadingDock: false,
                hasParking: true,
                accessHours: 'Lun–Vie 7:00 AM – 7:00 PM / Sáb 8:00 AM – 2:00 PM',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 5500000,
                capacityOccupied: 40,
            },
            {
                name: 'LogiStock Química D-04',
                description: 'Bodega especializada para sustancias químicas, inflamables y corrosivas. Construida bajo norma NFPA-30. Piso impermeabilizado con berma de contención, ventilación forzada cada 10 min, sistema de extinción automática tipo AFFF. Separación de incompatibles por celdas. Requiere ficha técnica SDS de cada producto.',
                warehouseType: 'QUIMICA',
                city: 'Barranquilla',
                address: 'Zona Industrial Metropolitana Km 8, Bodega 4',
                postalCode: '080001',
                storageLength: 30,
                storageWidth: 20,
                storageHeight: 6,
                usableArea: 520,
                utilitiesIncluded: false,
                utilitiesResponsible: 'COMPARTIDO',
                utilitiesDetails: 'Energía eléctrica compartida según medidor individual; Agua y Aseo por cuenta del arrendatario',
                hasSecuritySystem: true,
                hasLoadingDock: true,
                hasParking: true,
                accessHours: 'Lun–Vie 6:00 AM – 6:00 PM (acceso nocturno previa autorización)',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 6300000,
                capacityOccupied: 25,
            },
            {
                name: 'LogiStock Exterior E-05',
                description: 'Patio exterior pavimentado para almacenaje de maquinaria pesada, vehículos, contenedores ISO y materiales de construcción a granel. Acceso directo por vía primaria con altura libre de 7 m en pórtico de entrada. Cercado perimetral con concertina y circuito CCTV HD. Sin cubierta; no apto para mercancía sensible a lluvia.',
                warehouseType: 'EXTERIOR',
                city: 'Cali',
                address: 'Carretera Cali–Palmira Km 4, Parque Logístico Sur',
                postalCode: '760001',
                storageLength: 80,
                storageWidth: 40,
                storageHeight: null,
                usableArea: 2800,
                utilitiesIncluded: false,
                utilitiesResponsible: 'ARRENDATARIO',
                utilitiesDetails: 'Alumbrado externo incluido; energía para oficinas y agua por cuenta del arrendatario',
                hasSecuritySystem: true,
                hasLoadingDock: false,
                hasParking: true,
                accessHours: '24/7',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8ed7c83a7f?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 3800000,
                capacityOccupied: 55,
            },
            {
                name: 'LogiStock VIP Premium F-06',
                description: 'Espacio premium para mercancía de alto valor económico: joyería, electrónica de gama alta, vinos y licores, obras de arte. Control de acceso biométrico, cámaras 4K con retención de 90 días, alarma sísmica y personal de seguridad armado. Seguro de contenido incluido hasta USD 500,000. Climatización de precisión y humedad relativa constante.',
                warehouseType: 'VIP',
                city: 'Bogotá',
                address: 'Cra 7 #114-60, Torre Empresarial Chicó, Sótano 1',
                postalCode: '110221',
                storageLength: 15,
                storageWidth: 12,
                storageHeight: 3,
                usableArea: 160,
                utilitiesIncluded: true,
                utilitiesResponsible: 'ARRENDADOR',
                utilitiesDetails: 'Agua, Energía eléctrica, Gas, Aseo, Climatización, Internet fibra óptica',
                hasSecuritySystem: true,
                hasLoadingDock: false,
                hasParking: true,
                accessHours: '24/7 con cita previa para ingresos fuera de horario hábil',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 12000000,
                capacityOccupied: 20,
            },
            {
                name: 'LogiStock Sur G-07',
                description: 'Bodega de distribución de mediano formato, apta para e-commerce y comercio mayorista. Altillo metálico incluido que duplica el área útil. Rampas niveladoras hidráulicas. Zona de picking y packing habilitada con estanterías livianas. Acceso 24/7 con puerta motorizada.',
                warehouseType: 'GENERAL',
                city: 'Medellín',
                address: 'Calle 10 Sur #43C-85, Sabaneta',
                postalCode: '055450',
                storageLength: 35,
                storageWidth: 25,
                storageHeight: 7,
                usableArea: 800,
                utilitiesIncluded: true,
                utilitiesResponsible: 'ARRENDADOR',
                utilitiesDetails: 'Agua, Energía eléctrica',
                hasSecuritySystem: true,
                hasLoadingDock: true,
                hasParking: true,
                accessHours: '24/7',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 3900000,
                capacityOccupied: 70,
            },
            {
                name: 'LogiStock Congelados H-08',
                description: 'Cámara de congelación industrial (-18°C a -25°C) para helados, mariscos, carnes procesadas y productos de ultra-frío. Sistema de ciclo de refrigeración redundante. Pisos anestaciados y paredes de aluminio sanitario. Cumple BPM (Buenas Prácticas de Manufactura) y normas HACCP. Registro de temperatura en tiempo real accesible por app.',
                warehouseType: 'REFRIGERADA',
                city: 'Bucaramanga',
                address: 'Transversal 28 #48-65, Parque Industrial Bucaramanga',
                postalCode: '680003',
                storageLength: 18,
                storageWidth: 14,
                storageHeight: 4,
                usableArea: 220,
                utilitiesIncluded: false,
                utilitiesResponsible: 'COMPARTIDO',
                utilitiesDetails: 'Energía eléctrica se factura por submedidor; demás servicios incluidos en canon',
                hasSecuritySystem: true,
                hasLoadingDock: true,
                hasParking: false,
                accessHours: 'Lun–Sáb 4:00 AM – 11:00 PM',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 5900000,
                capacityOccupied: 80,
            },
            {
                name: 'LogiStock Occidente I-09',
                description: 'Nave industrial de gran formato para logística y cross-docking. Seis muelles de carga con plataforma niveladora. Puertas de 4 m × 4,5 m para contenedores de 40 pies. Sistema contra incendio por rociadores. Oficina administrativa de 30 m² incluida. Certificado BASC para operaciones de comercio exterior.',
                warehouseType: 'GENERAL',
                city: 'Cali',
                address: 'Av. Simón Bolívar #8AN-14, Aguablanca Industrial',
                postalCode: '760030',
                storageLength: 60,
                storageWidth: 40,
                storageHeight: 10,
                usableArea: 2200,
                utilitiesIncluded: true,
                utilitiesResponsible: 'ARRENDADOR',
                utilitiesDetails: 'Agua, Energía eléctrica, Gas industrial, Aseo',
                hasSecuritySystem: true,
                hasLoadingDock: true,
                hasParking: true,
                accessHours: '24/7',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8ed7c83a7f?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 9500000,
                capacityOccupied: 45,
            },
            {
                name: 'LogiStock Farmacéutico J-10',
                description: 'Bodega con condiciones controladas para medicamentos, reactivos de laboratorio y dispositivos médicos. Temperatura constante 15–25°C; humedad relativa < 60%. Validación de instalaciones para cumplir Manual de Buenas Prácticas de Almacenamiento (INVIMA). Registro de acceso por usuario y hora. Sin animales ni plaguicidas.',
                warehouseType: 'DELICADOS',
                city: 'Bogotá',
                address: 'Calle 26 #96-18, Centro Empresarial Salitre',
                postalCode: '110931',
                storageLength: 22,
                storageWidth: 18,
                storageHeight: 4,
                usableArea: 360,
                utilitiesIncluded: true,
                utilitiesResponsible: 'ARRENDADOR',
                utilitiesDetails: 'Agua, Energía eléctrica, HVAC, Internet, Aseo',
                hasSecuritySystem: true,
                hasLoadingDock: false,
                hasParking: true,
                accessHours: 'Lun–Vie 7:00 AM – 8:00 PM / Sáb 8:00 AM – 1:00 PM',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 6800000,
                capacityOccupied: 50,
            },
            {
                name: 'LogiStock Costa K-11',
                description: 'Bodega portuaria en zona de actividad logística de Cartagena. Integración directa con patios del Puerto de Cartagena (SPRC). Apta para almacenamiento temporal antes de embarque o después de desembarque. Cumple reglamentación DIAN para depósitos habilitados. Capacidad para contenedores llenos.',
                warehouseType: 'GENERAL',
                city: 'Cartagena',
                address: 'Manga, Zona Portuaria Lote 15, Vía al Puerto',
                postalCode: '130001',
                storageLength: 50,
                storageWidth: 30,
                storageHeight: 9,
                usableArea: 1350,
                utilitiesIncluded: false,
                utilitiesResponsible: 'ARRENDATARIO',
                utilitiesDetails: 'Todos los servicios públicos corren por cuenta del arrendatario',
                hasSecuritySystem: true,
                hasLoadingDock: true,
                hasParking: true,
                accessHours: '24/7',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 8200000,
                capacityOccupied: 30,
            },
            {
                name: 'LogiStock Pinturas L-12',
                description: 'Espacio habilitado para almacenamiento de pinturas, solventes, barnices y productos derivados del petróleo. Ventilación perimetral forzada. Instalaciones eléctricas antiexplosión (ATEX). Extintores polvo ABC y CO₂. Separación estricta de oxidantes. Temperatura máxima interna 30°C.',
                warehouseType: 'QUIMICA',
                city: 'Medellín',
                address: 'Carrera 65 #14-30, Zona Industrial Guayabal',
                postalCode: '050034',
                storageLength: 25,
                storageWidth: 15,
                storageHeight: 5,
                usableArea: 340,
                utilitiesIncluded: false,
                utilitiesResponsible: 'COMPARTIDO',
                utilitiesDetails: 'Energía por submedidor; agua incluida en canon',
                hasSecuritySystem: true,
                hasLoadingDock: true,
                hasParking: false,
                accessHours: 'Lun–Vie 7:00 AM – 5:00 PM',
                isAvailable: false,
                imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 4200000,
                capacityOccupied: 95,
            },
            {
                name: 'LogiStock Express M-13',
                description: 'Mini-bodega de baja rotación para startups y emprendedores. Ideal para stock de seguridad, archivos físicos o e-commerce de pequeño volumen. Sin muelle; uso de transpaleta manual. Se arrienda desde 1 mes. Incluye app LogiStock para registro de entradas y salidas.',
                warehouseType: 'GENERAL',
                city: 'Bogotá',
                address: 'Calle 116 #19-10, Local B-02, Usaquén',
                postalCode: '110121',
                storageLength: 10,
                storageWidth: 8,
                storageHeight: 3,
                usableArea: 72,
                utilitiesIncluded: true,
                utilitiesResponsible: 'ARRENDADOR',
                utilitiesDetails: 'Agua, Energía eléctrica, Internet, Aseo',
                hasSecuritySystem: true,
                hasLoadingDock: false,
                hasParking: false,
                accessHours: 'Lun–Sáb 7:00 AM – 8:00 PM',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8ed7c83a7f?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 1200000,
                capacityOccupied: 10,
            },
            {
                name: 'LogiStock Automotriz N-14',
                description: 'Patio techado de gran altura (12 m) destinado al almacenamiento de vehículos, repuestos voluminosos y llantas. Piso de concreto reforzado clase F7. Acceso con pluma automática para control de ingreso vehicular. Sin restricciones de tamaño para vehículos hasta 3,5 toneladas.',
                warehouseType: 'EXTERIOR',
                city: 'Cali',
                address: 'Autopista Sur km 2.5, Parque Industrial Acopi Yumbo',
                postalCode: '760030',
                storageLength: 60,
                storageWidth: 30,
                storageHeight: 12,
                usableArea: 1600,
                utilitiesIncluded: false,
                utilitiesResponsible: 'ARRENDATARIO',
                utilitiesDetails: 'Energía y agua facturadas directamente al arrendatario',
                hasSecuritySystem: true,
                hasLoadingDock: false,
                hasParking: true,
                accessHours: '24/7',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 5600000,
                capacityOccupied: 40,
            },
            {
                name: 'LogiStock Vinos O-15',
                description: 'Cava climatizada para vinos, espumantes y destilados premium. Temperatura estable 12–16°C, humedad 60–80%, alejada de vibraciones y luz UV. Racks de madera para botellas y pallets enológicos. Inventario digitalizado con código QR por añada y denominación. Seguros incluidos hasta COP 200M.',
                warehouseType: 'VIP',
                city: 'Bogotá',
                address: 'Carrera 11A #93-41, Zona Rosa',
                postalCode: '110221',
                storageLength: 12,
                storageWidth: 10,
                storageHeight: 3,
                usableArea: 110,
                utilitiesIncluded: true,
                utilitiesResponsible: 'ARRENDADOR',
                utilitiesDetails: 'Agua, Energía eléctrica, Climatización de precisión, Internet',
                hasSecuritySystem: true,
                hasLoadingDock: false,
                hasParking: false,
                accessHours: 'Lun–Vie 9:00 AM – 6:00 PM (acceso especial bajo solicitud)',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 9800000,
                capacityOccupied: 65,
            },
            {
                name: 'LogiStock Pereira P-16',
                description: 'Bodega estratégica en el eje cafetero para distribución regional a Risaralda, Quindío y Caldas. Conexión directa a la Autopista del Café. Dos andenes de descarga independientes. Puertas dobles con portón de 5 m de ancho. Ventilación cruzada natural. Ideal para industria alimentaria seca y consumo masivo.',
                warehouseType: 'GENERAL',
                city: 'Pereira',
                address: 'Av. 30 de Agosto #40-20, Parque Industrial La Badea',
                postalCode: '660001',
                storageLength: 45,
                storageWidth: 28,
                storageHeight: 8,
                usableArea: 1180,
                utilitiesIncluded: true,
                utilitiesResponsible: 'ARRENDADOR',
                utilitiesDetails: 'Agua, Energía eléctrica, Gas natural, Aseo',
                hasSecuritySystem: false,
                hasLoadingDock: true,
                hasParking: true,
                accessHours: 'Lun–Sáb 6:00 AM – 9:00 PM',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 3200000,
                capacityOccupied: 20,
            },
            {
                name: 'LogiStock Textiles Q-17',
                description: 'Almacén especializado para la industria textil y confección. Control de humedad relativa entre 45–55% para evitar deterioro de telas. Estanterías móviles tipo compactas para maximizar área. Zona de clasificación y empaque habilitada. Permite exhibición de muestras en sala adjunta de 20 m².',
                warehouseType: 'DELICADOS',
                city: 'Medellín',
                address: 'Carrera 52 #10-30, Centro Empresarial Fabricato',
                postalCode: '051040',
                storageLength: 28,
                storageWidth: 20,
                storageHeight: 5,
                usableArea: 520,
                utilitiesIncluded: true,
                utilitiesResponsible: 'ARRENDADOR',
                utilitiesDetails: 'Agua, Energía eléctrica, Control ambiental (HVAC), Aseo',
                hasSecuritySystem: true,
                hasLoadingDock: false,
                hasParking: true,
                accessHours: 'Lun–Sáb 7:00 AM – 7:00 PM',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8ed7c83a7f?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 4600000,
                capacityOccupied: 55,
            },
            {
                name: 'LogiStock Aeropuerto R-18',
                description: 'Bodega de última milla contigua al Aeropuerto El Dorado. Habilitada por DIAN para zona de carga aérea nacional e internacional. Servicio de pesaje certificado. Temperatura ambiente controlada. Personal certificado para manejo de carga peligrosa clase IATA (DGR). Disponible en turnos rotativos.',
                warehouseType: 'GENERAL',
                city: 'Bogotá',
                address: 'Av. El Dorado #103-15, Zona Cargo El Dorado',
                postalCode: '110931',
                storageLength: 30,
                storageWidth: 20,
                storageHeight: 6,
                usableArea: 540,
                utilitiesIncluded: true,
                utilitiesResponsible: 'ARRENDADOR',
                utilitiesDetails: 'Agua, Energía eléctrica, Internet fibra, Aseo',
                hasSecuritySystem: true,
                hasLoadingDock: true,
                hasParking: true,
                accessHours: '24/7',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 8600000,
                capacityOccupied: 38,
            },
            {
                name: 'LogiStock Agroindustria S-19',
                description: 'Bodega para insumos agropecuarios: fertilizantes, plaguicidas, semillas y agroquímicos. Cumple resolución ICA 449/1995. Ventilación lateral permanente, piso impermeable con drenaje perimetral, señalización de riesgo. Equipado con botiquín de emergencia y ducha de seguridad. No se permite mezcla con alimentos para consumo humano.',
                warehouseType: 'QUIMICA',
                city: 'Villavicencio',
                address: 'Km 3 Vía Acacías, Parque Agroindustrial Llanos',
                postalCode: '500001',
                storageLength: 35,
                storageWidth: 22,
                storageHeight: 6,
                usableArea: 720,
                utilitiesIncluded: false,
                utilitiesResponsible: 'ARRENDATARIO',
                utilitiesDetails: 'Todos los servicios públicos corren por cuenta del arrendatario',
                hasSecuritySystem: false,
                hasLoadingDock: true,
                hasParking: true,
                accessHours: 'Lun–Vie 6:00 AM – 5:00 PM / Sáb 7:00 AM – 12:00 PM',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 2900000,
                capacityOccupied: 15,
            },
            {
                name: 'LogiStock Multipropósito T-20',
                description: 'Complejo de bodegas modulares arrendables por fracción (desde 50 m²). Permite combinar módulos según crecimiento del cliente. Zona de administración compartida, cafetería, baños con vestier y parqueadero cubierto. Ideal para PYMES que necesitan flexibilidad de espacio. Opción de ampliar mes a mes sin penalidad.',
                warehouseType: 'GENERAL',
                city: 'Medellín',
                address: 'Calle 65 #55-60, Itagüí, Zona Industrial',
                postalCode: '055400',
                storageLength: 50,
                storageWidth: 40,
                storageHeight: 8,
                usableArea: 1800,
                utilitiesIncluded: true,
                utilitiesResponsible: 'ARRENDADOR',
                utilitiesDetails: 'Agua, Energía eléctrica, Gas natural, Aseo, Internet compartido',
                hasSecuritySystem: true,
                hasLoadingDock: true,
                hasParking: true,
                accessHours: 'Lun–Sáb 6:00 AM – 10:00 PM (24/7 disponible con plan Premium)',
                isAvailable: true,
                imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1000&auto=format&fit=crop',
                monthlyPrice: 4100000,
                capacityOccupied: 25,
            },
        ];

        for (const data of warehouseSeedData) {
            await Warehouse.findOrCreate({
                where: { name: data.name },
                defaults: data as any,
            });
        }
        console.log('✅ 20 Warehouses created.');

        console.log('⏳ Seeding sample Rentals...');
        const demoUser = await User.findOne({ where: { email: 'cliente1@gmail.com' } });
        const sampleWarehouses = await Warehouse.findAll({ limit: 3 });

        if (demoUser && sampleWarehouses.length > 0) {
            for (const warehouse of sampleWarehouses) {
                await Rental.findOrCreate({
                    where: { userId: demoUser.id, warehouseId: warehouse.id },
                    defaults: {
                        userId: demoUser.id,
                        warehouseId: warehouse.id,
                        startDate: new Date(),
                        monthlyAmount: 150000 + (Math.random() * 50000),
                        status: 'ACTIVE'
                    }
                });
            }
            console.log(`✅ 3 Rentals created for ${demoUser.email}.`);
        }

        console.log('🎉 Seeding finished successfully.');
        process.exit(0);
    } catch (error) {
        console.error('❌ Error executing seeder:', error);
        process.exit(1);
    }
};

seedDatabase();

