/**
 * warehouseSeeder.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Script para poblar la tabla `warehouses` con 30 bodegas reales y variadas.
 * Cubre todos los tipos: GENERAL, REFRIGERADA, DELICADOS, QUIMICA, EXTERIOR, VIP.
 * Cada bodega tiene nombre descriptivo, descripción detallada y atributos completos.
 *
 * Ejecución:
 *   npx tsx src/seeds/warehouseSeeder.ts
 * ─────────────────────────────────────────────────────────────────────────────
 */

import sequelize from '../config/database.js';
import { Warehouse } from '../models/index.js';

const warehouses = [
    // ══════════════════════════════════════════════════════════
    //  GENERAL — Almacenamiento seco, consumo masivo, distribución
    // ══════════════════════════════════════════════════════════
    {
        name: 'Distribuidora Seca Industrial — Medellín Norte',
        description:
            'Bodega de uso general de 1 200 m² útiles, ubicada en la zona industrial norte de Medellín, ideal para almacenamiento y distribución de bienes secos de consumo masivo: alimentos no perecederos, bebidas envasadas, artículos de papelería, calzado y textiles. Piso de concreto reforzado clase F5 con capacidad de carga de 5 t/m². Iluminación LED con sensor de movimiento a 8 m de altura libre. Cuenta con 3 muelles de carga con rampas niveladoras hidráulicas, portones de 4,5 m × 4,5 m y puertas peatonales de emergencia certificadas. Sistema de rociadores antiincendio en toda la nave. CCTV HD 24/7, alarma perimetral y bodeguero de seguridad en turno nocturno. Zona de picking/packing habilitada con estanterías metálicas tipo rack selectivo de 6 niveles. Oficina administrativa de 25 m² incluida. Sin restricciones de temperatura. Certificado BASC para cadena de suministro segura.',
        warehouseType: 'GENERAL',
        city: 'Medellín',
        address: 'Calle 78 #28-45, Zona Industrial Norte',
        postalCode: '050001',
        storageLength: 50,
        storageWidth: 24,
        storageHeight: 8,
        usableArea: 1200,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua potable, energía eléctrica trifásica, alumbrado exterior y aseo semanal',
        hasSecuritySystem: true,
        hasLoadingDock: true,
        hasParking: true,
        accessHours: '24/7',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8ed7c83a7f?q=80&w=1000',
        monthlyPrice: 5_200_000,
        capacityOccupied: 28,
    },
    {
        name: 'Centro Logístico E-Commerce — Bogotá Salitre',
        description:
            'Nave logística de 850 m² diseñada para operadores de e-commerce y comercio electrónico de mediano volumen. Situada a 2 km del aeropuerto El Dorado, con acceso directo por la Av. El Dorado. Altillo metálico de 200 m² instalado que duplica el área útil de almacenamiento. Zonas claramente delimitadas: recepción de mercancía, almacenamiento selectivo, área de devoluciones y despacho de pedidos. Conveyor de cinta para clasificación de bultos incluido. Dos rampas de carga. Conexión a fibra óptica de 500 Mbps para integración con WMS. Control de acceso con tarjeta RFID por área. Parqueadero cubierto para 10 vehículos de carga liviana. Temperatura ambiente sin climatización activa; ventilación cruzada natural garantiza máx. 28 °C en verano. No apto para sustancias inflamables ni cadena de frío.',
        warehouseType: 'GENERAL',
        city: 'Bogotá',
        address: 'Av. El Dorado #101-20, Parque Empresarial Salitre',
        postalCode: '110931',
        storageLength: 40,
        storageWidth: 22,
        storageHeight: 7,
        usableArea: 850,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua, energía eléctrica 220/380 V, Internet fibra 500 Mbps, aseo diario',
        hasSecuritySystem: true,
        hasLoadingDock: true,
        hasParking: true,
        accessHours: 'Lun–Vie 6:00 AM – 10:00 PM / Sáb–Dom 7:00 AM – 6:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=1000',
        monthlyPrice: 4_400_000,
        capacityOccupied: 45,
    },
    {
        name: 'Bodega Cross-Docking Portuario — Cartagena Manga',
        description:
            'Instalación de 1 500 m² habilitada por la DIAN como depósito temporal de mercancía en tránsito, adosada a los patios del Puerto de Cartagena (SPRC). Perfecta para operadores de comercio exterior que requieren clasificar, re-etiquetar y consolidar carga entre contenedores antes del re-embarque o la distribución nacional. Seis andenes de descarga independientes con desnivel para camiones de 2 ejes y tractomulas. Puertas tipo cortina de PVC industrial. Báscula de piso certificada de 60 t. Refrigeración de emergencia portátil disponible como servicio adicional. Certificación ISO 28001 para seguridad en la cadena de suministro. No incluye almacenamiento prolongado (>30 días) sin previa autorización aduanera.',
        warehouseType: 'GENERAL',
        city: 'Cartagena',
        address: 'Manga, Zona Portuaria Lote 15, Vía al Puerto SPRC',
        postalCode: '130001',
        storageLength: 60,
        storageWidth: 25,
        storageHeight: 9,
        usableArea: 1500,
        utilitiesIncluded: false,
        utilitiesResponsible: 'ARRENDATARIO',
        utilitiesDetails: 'Todos los servicios públicos a cargo del arrendatario; medidores individuales instalados',
        hasSecuritySystem: true,
        hasLoadingDock: true,
        hasParking: true,
        accessHours: '24/7',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8ed7c83a7f?q=80&w=1000',
        monthlyPrice: 9_800_000,
        capacityOccupied: 32,
    },
    {
        name: 'MiniStore PYME Modular — Bogotá Usaquén',
        description:
            'Espacio de almacenamiento flexible de 80 m² pensado para startups, PYMES y emprendedores de e-commerce que necesitan su primer inventario externo. Arrendamiento desde 1 mes sin penalidad por salida anticipada. Sin acceso a muelle; uso de transpaletas manuales disponibles en préstamo. Vigilancia privada en el edificio, cámara en puerta de cada local. Temperatura ambiente. Servicio de recepción de paquetes incluido en horario hábil: el operador del parque recibe la mercancía en ausencia del cliente. App LogiStock para registro digital de ingresos y salidas. No se permiten líquidos inflamables, gases a presión ni sustancias de olor fuerte.',
        warehouseType: 'GENERAL',
        city: 'Bogotá',
        address: 'Calle 116 #19-10, Local B-04, Edificio LogiPark Usaquén',
        postalCode: '110121',
        storageLength: 10,
        storageWidth: 8,
        storageHeight: 3,
        usableArea: 80,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua, energía eléctrica monofásica, Internet compartido y aseo semanal',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: false,
        accessHours: 'Lun–Sáb 7:00 AM – 8:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=1000',
        monthlyPrice: 1_100_000,
        capacityOccupied: 10,
    },
    {
        name: 'Nave Industrial Gran Formato — Cali Yumbo',
        description:
            'Gran nave industrial de 2 400 m² situada en el Parque Industrial Acopi-Yumbo, considerado el mejor corredor logístico del suroccidente colombiano. Techo a dos aguas con claraboya corrida para iluminación natural. Ocho muelles de carga con plataformas niveladoras eléctricas, acceso para contenedores ISO de 40 pies. Capacidad de carga de piso 8 t/m². Sistema contra incendio por rociadores wet-pipe con central de monitoreo. Dos oficinas administrativas de 40 m² c/u. Patio de maniobras de 3 000 m² para articulados. Energía eléctrica trifásica de 440 V con transformador propio. Ideal para manufactura, ensamble liviano o distribución regional del Valle del Cauca.',
        warehouseType: 'GENERAL',
        city: 'Cali',
        address: 'Autopista Sur km 2.5, Parque Industrial Acopi-Yumbo, Bodega 12',
        postalCode: '763030',
        storageLength: 80,
        storageWidth: 30,
        storageHeight: 11,
        usableArea: 2400,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua, energía trifásica 440 V, gas natural, aseo mensual de áreas comunes',
        hasSecuritySystem: true,
        hasLoadingDock: true,
        hasParking: true,
        accessHours: '24/7',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1000',
        monthlyPrice: 11_500_000,
        capacityOccupied: 20,
    },
    {
        name: 'Bodega Eje Cafetero Distribución — Pereira La Badea',
        description:
            'Bodega estratégica de 1 260 m² en el Parque Industrial La Badea, puerta de entrada al triángulo cafetero que conecta Risaralda, Quindío y Caldas. Acceso directo a la Autopista del Café y la doble calzada Pereira-Manizales. Dos andenes de descarga independientes con portones de 4,5 m de ancho. Piso de concreto pulido, ciclovías internas para montacargas hasta 3 t. Sala de reuniones de 18 m² disponible para clientes. Ventilación cruzada natural manteniendo temperatura ≤ 30 °C. Apta para alimentos secos, bebidas, materiales de construcción livianos, ropa y calzado. Sin climatización activa.',
        warehouseType: 'GENERAL',
        city: 'Pereira',
        address: 'Av. 30 de Agosto #40-20, Parque Industrial La Badea',
        postalCode: '660001',
        storageLength: 45,
        storageWidth: 28,
        storageHeight: 8,
        usableArea: 1260,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua, energía eléctrica, gas natural y aseo de áreas comunes',
        hasSecuritySystem: false,
        hasLoadingDock: true,
        hasParking: true,
        accessHours: 'Lun–Sáb 6:00 AM – 9:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8ed7c83a7f?q=80&w=1000',
        monthlyPrice: 3_500_000,
        capacityOccupied: 18,
    },

    // ══════════════════════════════════════════════════════════
    //  REFRIGERADA — Cadena de frío y congelación
    // ══════════════════════════════════════════════════════════
    {
        name: 'Cámara Refrigerada Lácteos y Carnes — Bogotá Fontibón',
        description:
            'Cuarto frío de 480 m² útiles para almacenamiento de productos perecederos en cadena de frío continua: lácteos (leche, quesos, mantequilla), carnes frescas, embutidos y productos de cuarta gama (vegetales procesados listos para consumo). Temperatura operativa controlada entre 0 °C y 4 °C con variación máxima de ±0,5 °C. Sistema de refrigeración principal con compresor doble scroll + unidad de respaldo diésel que activa automáticamente ante corte de energía (UPS de 30 min de autonomía). Paredes de panel sándwich de 100 mm de poliuretano inyectado. Antecámara termobuffer de 40 m² a 8 °C para pre-enfriamiento de mercancía caliente. HACCP implementado con registro de temperatura en nube cada 5 minutos. Certificación INVIMA vigente. Piso antideslizante y antibacterial. Andén cubierto para camiones refrigerados.',
        warehouseType: 'REFRIGERADA',
        city: 'Bogotá',
        address: 'Av. Boyacá #70-15, Zona Franca Fontibón, Módulo C',
        postalCode: '110931',
        storageLength: 30,
        storageWidth: 16,
        storageHeight: 5,
        usableArea: 480,
        utilitiesIncluded: false,
        utilitiesResponsible: 'COMPARTIDO',
        utilitiesDetails: 'Energía eléctrica facturada por submedidor individual; agua y aseo incluidos en canon',
        hasSecuritySystem: true,
        hasLoadingDock: true,
        hasParking: true,
        accessHours: 'Lun–Sáb 4:00 AM – 11:00 PM / Dom previa autorización',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=1000',
        monthlyPrice: 8_200_000,
        capacityOccupied: 55,
    },
    {
        name: 'Túnel de Congelación Industrial — Barranquilla Zona Franca',
        description:
            'Instalación de ultracongelación y congelación profunda de 320 m² para mariscos, pescados, pulpos, cocochas y cortes de res exportados. Temperatura de operación de -18 °C a -25 °C con descenso controlado hasta -35 °C para túnel de congelamiento rápido (IQF) de productos individuales. Sistema de refrigeración por amoníaco NH₃ grado industrial con detection de fugas automático. Paredes en aluminio sanitario grado alimentario. Certificado BRC (British Retail Consortium) actualizaciones anuales. Integración con cámara de choque térmico de 40 m² a -12 °C. Equipo de pesaje de alta precisión ±5 g. No se aceptan productos sin envasado sellado. Requiere prenotificación de entrada con 48 h de anticipación para protocolos HACCP.',
        warehouseType: 'REFRIGERADA',
        city: 'Barranquilla',
        address: 'Zona Franca Industrial de Barranquilla, Bodega 7, Km 4 Vía Puerto',
        postalCode: '080020',
        storageLength: 20,
        storageWidth: 16,
        storageHeight: 5,
        usableArea: 320,
        utilitiesIncluded: false,
        utilitiesResponsible: 'ARRENDATARIO',
        utilitiesDetails: 'Energía eléctrica (alta demanda por refrigeración) y agua por cuenta del arrendatario',
        hasSecuritySystem: true,
        hasLoadingDock: true,
        hasParking: false,
        accessHours: 'Lun–Sáb 3:00 AM – 11:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1000',
        monthlyPrice: 7_600_000,
        capacityOccupied: 72,
    },
    {
        name: 'Bodega Farmacéutica Temperatura Controlada — Medellín El Poblado',
        description:
            'Espacio de 250 m² acondicionado exclusivamente para productos farmacéuticos, biológicos y vacunas que requieren cadena de frío ininterrumpida. Temperatura mantenida entre 2 °C y 8 °C según Farmacopea Internacional. Climatización de precisión con dos unidades Split redundantes. Registrador de datos calibrado ONAC con exportación automática para auditorías INVIMA. Control de humedad relativa ≤ 60%. Área de cuarentena separada por tabique, zona de rechazos identificada. Personal operativo con formación en Buenas Prácticas de Distribución (BPD). No se aceptan medicamentos de control especial sin permiso MINSALUD. Acceso restringido a personal autorizado con huella digital.',
        warehouseType: 'REFRIGERADA',
        city: 'Medellín',
        address: 'Calle 10 #43D-20, Edificio BioMed Centro, Piso 1, El Poblado',
        postalCode: '050021',
        storageLength: 20,
        storageWidth: 13,
        storageHeight: 4,
        usableArea: 250,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua, energía eléctrica, climatización, Internet fibra y aseo diario certificado',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: true,
        accessHours: 'Lun–Vie 7:00 AM – 7:00 PM / Emergencias: línea 24/7',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=1000',
        monthlyPrice: 7_900_000,
        capacityOccupied: 42,
    },
    {
        name: 'Cámara Floral y Hortofrutícola — Bogotá Corabastos',
        description:
            'Bodega refrigerada de 380 m² diseñada para flores de corte, frutas exóticas, vegetales y hierbas aromáticas con temperatura variable según producto (2–10 °C). Adosada a la Central de Abastos Corabastos, permite cargue y descargue en el mismo parque mayorista. Sistema de control por zonas independientes: dos cámaras de 150 m² c/u con set-point individual. Humedad relativa mantenida entre 85–95% para flores. Circulación de aire forzada que evita la formación de étileno. Plataforma elevadora para camionetas refrigeradas. Certificada por el ICA para exportación de flores. No apta para carne cruda ni derivados lácteos por riesgo de contaminación cruzada.',
        warehouseType: 'REFRIGERADA',
        city: 'Bogotá',
        address: 'Av. Carrera 80 #2-51, Corabastos, Nave Este 3',
        postalCode: '111611',
        storageLength: 25,
        storageWidth: 16,
        storageHeight: 4,
        usableArea: 380,
        utilitiesIncluded: false,
        utilitiesResponsible: 'COMPARTIDO',
        utilitiesDetails: 'Submedidor de energía para refrigeración; agua y aseo incluidos en la tarifa mensual',
        hasSecuritySystem: true,
        hasLoadingDock: true,
        hasParking: true,
        accessHours: 'Lun–Sáb 3:00 AM – 10:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=1000',
        monthlyPrice: 6_300_000,
        capacityOccupied: 60,
    },

    // ══════════════════════════════════════════════════════════
    //  DELICADOS — Electrónica, arte, textiles, documentos
    // ══════════════════════════════════════════════════════════
    {
        name: 'Bóveda Electrónica y Componentes — Medellín Parque Empresarial',
        description:
            'Espacio de 310 m² especialmente acondicionado para almacenamiento de equipos electrónicos de alta gama, semiconductores, circuitos integrados y pantallas LCD/OLED. Piso epóxico antiestático con resistencia máxima de 10⁶ Ω para protección contra descargas electroestáticas (ESD). Temperatura constante 20 ± 2 °C con humedad relativa de 40–55% mediante sistema HVAC de precisión. UPS con baterías de litio que garantizan 2 h de autonomía ante fallas eléctricas. Luz UV anti-UV-B filtrada para evitar degradación de polímeros. Control de acceso por huella dactilar; registro de entrada y salida por operario auditado. Prohibido el ingreso con calzado de suela metálica, imanes industriales o herramientas magnéticas. Sistema de extinción limpia (gas Novec™ 1230) sin riesgo para equipos activos.',
        warehouseType: 'DELICADOS',
        city: 'Medellín',
        address: 'Carrera 48 #18-20, Edificio LogiPark, Módulo D, Piso 1',
        postalCode: '050024',
        storageLength: 22,
        storageWidth: 14,
        storageHeight: 4,
        usableArea: 310,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua, energía eléctrica regulada, HVAC de precisión, UPS y aseo diario libre de polvo',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: true,
        accessHours: 'Lun–Vie 7:00 AM – 7:00 PM / Sáb 8:00 AM – 2:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=1000',
        monthlyPrice: 6_100_000,
        capacityOccupied: 35,
    },
    {
        name: 'Almacén Textil y Confección Especializado — Medellín Fabricato',
        description:
            'Local de 560 m² para la industria textil exportadora. Humedad relativa controlada entre 45–55% para evitar el deterioro de fibras naturales (algodón, lana, seda) y técnicas (poliéster, nylon). Estanterías tipo compactas móviles de alta densidad que permiten almacenar el doble de SKU frente a estanterías fijas. Zona de clasificación y etiquetado de 60 m². Sala de muestras de 22 m² con iluminación D65 normalizada para revisión de colores. Acceso elevador de carga de 2 t. Personal de manipulación con guantes de algodón obligatorios. Prohibidos cosméticos, perfumes y aceites cerca de las telas. Certificado como proveedor de cadena de suministro para marcas de moda internacional.',
        warehouseType: 'DELICADOS',
        city: 'Medellín',
        address: 'Carrera 52 #10-30, Centro Empresarial Fabricato, Local 108',
        postalCode: '051040',
        storageLength: 28,
        storageWidth: 20,
        storageHeight: 5,
        usableArea: 560,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua, energía eléctrica, HVAC de control de humedad, iluminación D65 e Internet',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: true,
        accessHours: 'Lun–Sáb 7:00 AM – 7:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8ed7c83a7f?q=80&w=1000',
        monthlyPrice: 5_200_000,
        capacityOccupied: 50,
    },
    {
        name: 'Centro de Custodia de Documentos — Bogotá Centro Internacional',
        description:
            'Archivo físico de alta seguridad de 180 m² para custodia de documentos legales, históricos y expedientes corporativos. Temperatura controlada 18–22 °C, humedad relativa 45–55% para preservación de papel durante décadas. Estanterías metálicas abiertas ISO 11799. Extinción por gas CO₂ dirigido, sin rociadores de agua que dañarían expedientes. Control de acceso biométrico con log de auditoría inmutable. Inventario digitalizado con código de barras por caja y folio. Servicio de consulta con entrega el mismo día o escaneado de documentos bajo solicitud. Sin ventanas al exterior para protección contra luz UV. Prohibida la entrada con líquidos o alimentos. Cumple NTC 4436 (Norma Técnica Colombiana de Archivos).',
        warehouseType: 'DELICADOS',
        city: 'Bogotá',
        address: 'Calle 26 #13-49, Torre Avianca Piso B1, Centro Internacional',
        postalCode: '110311',
        storageLength: 18,
        storageWidth: 10,
        storageHeight: 4,
        usableArea: 180,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua, energía eléctrica regulada, aire acondicionado de precisión, extinción y aseo',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: false,
        accessHours: 'Lun–Vie 8:00 AM – 6:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=1000',
        monthlyPrice: 3_800_000,
        capacityOccupied: 70,
    },
    {
        name: 'Sala de Custodia Obras de Arte — Cali Santa Mónica',
        description:
            'Espacio climatizado de 140 m² para almacenamiento seguro de obras de arte, esculturas, antigüedades y colecciones privadas. Temperatura estable 18–21 °C con variación máxima ±0,5 °C; humedad relativa 50–55% para prevenir deformación de lienzos y corrosión de bronce. Iluminación actimica (sin UV ni IR emisivo) con luxes < 50 para obras fotosensibles. Cámaras 4K de cobertura total con retención de 120 días. Acceso únicamente acompañado por personal autorizado; registro fotográfico de ingreso/egreso de cada pieza. Estanterías acolchadas y caballetes especiales. Servicio de catalogación digital incluido por obra. Seguro de contenido disponible hasta USD 2 000 000 (cobro adicional). Prohibida la manipulación sin guantes de algodón sin pelusa.',
        warehouseType: 'DELICADOS',
        city: 'Cali',
        address: 'Carrera 98 #18-48, Zona Residencial Santa Mónica, Edificio ArtVault',
        postalCode: '760032',
        storageLength: 14,
        storageWidth: 10,
        storageHeight: 3,
        usableArea: 140,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Energía eléctrica regulada, climatización de precisión, humidificador/deshumidificador, Internet y aseo especializado',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: false,
        accessHours: 'Lun–Vie 9:00 AM – 5:00 PM (emergencias con previa autorización)',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=1000',
        monthlyPrice: 8_500_000,
        capacityOccupied: 25,
    },

    // ══════════════════════════════════════════════════════════
    //  QUÍMICA — Sustancias peligrosas, inflamables, agroquímicos
    // ══════════════════════════════════════════════════════════
    {
        name: 'Bodega NFPA-30 Inflamables y Solventes — Barranquilla ZIP',
        description:
            'Bodega diseñada y construida bajo la norma NFPA-30 (Flammable and Combustible Liquids Code) para almacenamiento de pinturas, solventes, barnices, adhesivos y derivados del petróleo. Piso impermeabilizado con epóxico resistente a hidrocarburos y berma de contención perimetral calculada para el 110% del volumen del mayor contenedor. Ventilación forzada mecánica con un mínimo de 6 renovaciones/hora para mantener concentración de vapores < 25% LIE. Instalaciones eléctricas tipo ATEX Zona 1 (antiexplosión). Sistema automático de detección de gases inflamables con alarma y apertura de extractores. Extinción por polvo ABC y CO₂. Estanterías de acero inoxidable sin tierra eléctrica expuesta. Celdas separadas para incompatibles (oxidantes vs inflamables). Requiere ficha SDS actualizada de cada producto. Capacidad máxima 420 m³ de mezcla de clases IA–IB–II.',
        warehouseType: 'QUIMICA',
        city: 'Barranquilla',
        address: 'Zona Industrial Metropolitana ZIP, Km 8 Vía Malambo, Módulo Q-4',
        postalCode: '080020',
        storageLength: 30,
        storageWidth: 18,
        storageHeight: 6,
        usableArea: 540,
        utilitiesIncluded: false,
        utilitiesResponsible: 'COMPARTIDO',
        utilitiesDetails: 'Energía eléctrica por submedidor individual; agua y aseo incluidos; gas no disponible',
        hasSecuritySystem: true,
        hasLoadingDock: true,
        hasParking: true,
        accessHours: 'Lun–Vie 6:00 AM – 6:00 PM (acceso nocturno solo con autorización escrita)',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1000',
        monthlyPrice: 6_800_000,
        capacityOccupied: 30,
    },
    {
        name: 'Depósito Agroquímicos ICA — Villavicencio Parque Agroindustrial',
        description:
            'Bodega habilitada para el almacenamiento de insumos agropecuarios registrados ante el ICA: plaguicidas de uso agrícola, fertilizantes, herbicidas, fungicidas y semillas certificadas. Cumple Resolución ICA 449/1995 y el reglamento técnico de almacenamiento de plaguicidas. Piso de concreto impermeable con drenaje perimetral hacia trampa de grasas. Ventilación natural cruzada y ventilación mecánica de refuerzo. Señalización de peligro NFPA 704. Botiquín de emergencia tipo B y ducha de descontaminación en el exterior. Separación física entre fertilizantes nitrogenados y plaguicidas. No se permite mezcla con alimentos para consumo humano ni productos veterinarios sin aislamiento. Registro de inventario y trazabilidad por lote y número de ICA exigido.',
        warehouseType: 'QUIMICA',
        city: 'Villavicencio',
        address: 'Km 3 Vía Acacías, Parque Agroindustrial Llanos Orientales, Bodega 5',
        postalCode: '500001',
        storageLength: 35,
        storageWidth: 22,
        storageHeight: 6,
        usableArea: 770,
        utilitiesIncluded: false,
        utilitiesResponsible: 'ARRENDATARIO',
        utilitiesDetails: 'Todos los servicios públicos (agua, energía, aseo especial) a cargo del arrendatario',
        hasSecuritySystem: false,
        hasLoadingDock: true,
        hasParking: true,
        accessHours: 'Lun–Vie 6:00 AM – 5:00 PM / Sáb 7:00 AM – 12:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8ed7c83a7f?q=80&w=1000',
        monthlyPrice: 3_100_000,
        capacityOccupied: 15,
    },
    {
        name: 'Almacén Reactivos Laboratorio — Bogotá Ciudad Universitaria',
        description:
            'Espacio de 220 m² dedicado a reactivos químicos de laboratorio, ácidos, bases, disolventes HPLC, gases especiales y productos de diagnóstico in vitro. Temperatura controlada 15–20 °C con unidad de frío de respaldo. Armarios de seguridad para ácidos y bases (separados entre sí). Campana extractora de gases de 2 m de longitud disponible para trasvase. Instalaciones antiexplosión para gases inflamables (H₂, acetileno). Inventario gestionado bajo NTC-ISO 17025 con trazabilidad de lote y fecha de vencimiento. Acceso exclusivo a profesionales con licencia química vigente. Área de neutralización de residuos incluida. Cumple reglamentación del Ministerio de Salud e INVIMA para sustancias de control.',
        warehouseType: 'QUIMICA',
        city: 'Bogotá',
        address: 'Carrera 30 #45-03, Ciudad Universitaria, Edificio Ciencias, Sótano 2',
        postalCode: '111311',
        storageLength: 18,
        storageWidth: 12,
        storageHeight: 4,
        usableArea: 220,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua purificada, energía regulada, HVAC, extracción forzada, aseo especializado e Internet',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: false,
        accessHours: 'Lun–Vie 7:00 AM – 9:00 PM / Sáb 8:00 AM – 2:00 PM',
        isAvailable: false,
        imageUrl: 'https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=1000',
        monthlyPrice: 5_500_000,
        capacityOccupied: 88,
    },

    // ══════════════════════════════════════════════════════════
    //  EXTERIOR — Patios, maquinaria, contenedores, vehículos
    // ══════════════════════════════════════════════════════════
    {
        name: 'Patio Contenedores y Maquinaria Pesada — Cali Sur',
        description:
            'Patio pavimentado de 3 200 m² sin cubierta, ideal para parqueo y almacenamiento temporal de contenedores ISO de 20 y 40 pies, maquinaria de construcción (excavadoras, retroexcavadoras, volquetas), grúas articuladas y materiales de obra a granel. Acceso por portón doble de 8 m de ancho para vehículos articulados de hasta 40 t. Iluminación perimetral LED para operación nocturna. Cercado con malla eslabonada de 3 m con concertina. CCTV HD cobertura 100% del patio. Capacidad estimada: 80 contenedores de 40 pies apilados 2 de alto. Se presta servicio de maniobra con grúa reach-stacker (costo adicional). No apta para sustancias peligrosas sin aprobación previa. Sin cubierta: no usar para mercancía sensible a lluvia.',
        warehouseType: 'EXTERIOR',
        city: 'Cali',
        address: 'Carretera Cali–Palmira Km 3.5, Parque Logístico Sur, Lote 8',
        postalCode: '760001',
        storageLength: 80,
        storageWidth: 40,
        storageHeight: null,
        usableArea: 3200,
        utilitiesIncluded: false,
        utilitiesResponsible: 'ARRENDATARIO',
        utilitiesDetails: 'Alumbrado LED externo incluido; energía para oficinas y agua potable a cargo del arrendatario',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: true,
        accessHours: '24/7',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1604754742629-3e5728249d73?q=80&w=1000',
        monthlyPrice: 4_500_000,
        capacityOccupied: 40,
    },
    {
        name: 'Patio Techado Vehículos y Repuestos Pesados — Medellín Guayabal',
        description:
            'Nave exterior semi-cubierta de 1 800 m² con techo metálico a una agua, altura libre de 12 m en la cumbrera para maniobras con grúa tipo polipasto de 5 t instalada en viga carrilera. Destinada al almacenamiento de vehículos comerciales (tractomulas, buses, camiones >3,5 t), repuestos de gran formato y llantas. Piso de concreto reforzado clase F7 con capacidad de 10 t/m². Acceso con pluma automática y báscula de entrada. Zona de lavado de vehículos con trampa de grasas y separador de hidrocarburos. Punto de conexión eléctrica para cargadores de baterías o equipos de diagnóstico. No se permite reparación de motores, soldadura ni trasvase de lubricantes dentro del patio.',
        warehouseType: 'EXTERIOR',
        city: 'Medellín',
        address: 'Carrera 65 #36-20, Zona Industrial Guayabal, Nave 3',
        postalCode: '050034',
        storageLength: 60,
        storageWidth: 30,
        storageHeight: 12,
        usableArea: 1800,
        utilitiesIncluded: false,
        utilitiesResponsible: 'ARRENDATARIO',
        utilitiesDetails: 'Energía eléctrica y agua bajo medidor propio; alumbrado de seguridad incluido',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: true,
        accessHours: '24/7',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1581094271901-8022df4466f9?q=80&w=1000',
        monthlyPrice: 6_200_000,
        capacityOccupied: 55,
    },
    {
        name: 'Depósito Materiales Construcción a Cielo Abierto — Bucaramanga',
        description:
            'Lote pavimentado de 2 000 m² destinado al almacenamiento de materiales de construcción voluminosos o a granel: arena de río y concreto, grava, gravilla, tubería PVC y hierro de refuerzo, bloques, adoquines y prefabricados. Acceso para volquetas de doble troque y camiones mezcladores. Sin cubierta; no apto para cemento empacado, yeso ni materiales sensibles a la humedad sin lona de protección. Zona delimitada por producto con señalización vial interna. Báscula camionera certificada de 80 t. Dos cargadores de oruga disponibles como servicio adicional por hora. Cercado perimetral con guardia de seguridad en turno diurno.',
        warehouseType: 'EXTERIOR',
        city: 'Bucaramanga',
        address: 'Transversal 28 #50-10, Parque Industrial Bucaramanga, Lote 12',
        postalCode: '680001',
        storageLength: 50,
        storageWidth: 40,
        storageHeight: null,
        usableArea: 2000,
        utilitiesIncluded: false,
        utilitiesResponsible: 'ARRENDATARIO',
        utilitiesDetails: 'Agua y energía a cargo del arrendatario; iluminación perimetral incluida',
        hasSecuritySystem: false,
        hasLoadingDock: false,
        hasParking: true,
        accessHours: 'Lun–Sáb 5:00 AM – 7:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1590345799526-bafba91d2ff8?q=80&w=1000',
        monthlyPrice: 2_800_000,
        capacityOccupied: 48,
    },

    // ══════════════════════════════════════════════════════════
    //  VIP — Alta seguridad, alto valor, condiciones premium
    // ══════════════════════════════════════════════════════════
    {
        name: 'Bóveda Premium Joyería y Metales — Bogotá Chicó',
        description:
            'Espacio de máxima seguridad de 120 m² para almacenamiento de joyería fina, metales preciosos (oro, plata, platino en lingotes o menaje), gemología, relojes de lujo y bienes personales de muy alto valor. Paredes de concreto armado de 40 cm con acero inoxidable interior. Control de acceso multifactor: PIN + huella dactilar + reconocimiento facial con tiempo de espera antirrobo de 30 segundos. Cámaras 4K con IA de detección de movimiento y alarma silenciosa directa a la policía. Retención de video 90 días. Custodia activa por personal de seguridad armado las 24 h. Temperatura 20 ± 1 °C, HR 45–50%. Inventario con fotografía de alta resolución por pieza. Seguro de contenido incluido hasta USD 500 000 (cobertura mayor disponible). Acceso solo con cita previa y verificación de identidad.',
        warehouseType: 'VIP',
        city: 'Bogotá',
        address: 'Cra 7 #114-60, Torre Empresarial Chicó Norte, Sótano VIP',
        postalCode: '110221',
        storageLength: 12,
        storageWidth: 10,
        storageHeight: 3,
        usableArea: 120,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Energía regulada con UPS dedicado, climatización, Internet fibra y aseo especializado diario',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: true,
        accessHours: '24/7 solo con cita previa y verificación de identidad',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1601581875039-e899893d520c?q=80&w=1000',
        monthlyPrice: 15_000_000,
        capacityOccupied: 18,
    },
    {
        name: 'Cava de Vinos y Destilados Premium — Bogotá Zona Rosa',
        description:
            'Bodega climatizada de 130 m² destinada exclusivamente al almacenamiento de vinos de guarda, espumosos de primera fermentación, whiskies añejados y destilados premium de colección. Temperatura estable 13–16 °C con oscilación máxima de ±0,3 °C; humedad relativa 65–75% para preservación de corchos. Vibraciones < 0,1 mm/s para evitar alteración del sedimento. Ausencia total de luz UV; iluminación LED de espectro cálido <3 000 K. Racks de madera de roble americano para botella individual y pallets enológicos para cajas de 6 y 12 unidades. Inventario digitalizado con código QR por botella con registro de añada, denominación y puntaje crítico. Gestión de temperatura accesible vía app móvil con alertas en tiempo real. Sin acceso a terceros sin autorización expresa del titular. Seguro de contenido hasta COP 300 M.',
        warehouseType: 'VIP',
        city: 'Bogotá',
        address: 'Carrera 11A #93-41, Centro Comercial Zona Rosa, Nivel -1, Cava B',
        postalCode: '110221',
        storageLength: 13,
        storageWidth: 10,
        storageHeight: 3,
        usableArea: 130,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Energía eléctrica, climatización de precisión, humidificador, Internet fibra y limpieza especializada semanal',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: false,
        accessHours: 'Lun–Vie 9:00 AM – 6:00 PM (acceso fuera de horario con previa solicitud)',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1000',
        monthlyPrice: 10_500_000,
        capacityOccupied: 60,
    },
    {
        name: 'Hub Tecnológico Servidores y Data — Medellín Ruta N',
        description:
            'Suite de 200 m² de nivel Tier II+ para almacenamiento seguro de servidores blade, equipos de networking, NAS corporativos y hardware TI crítico. Piso técnico elevado de 60 cm para cableado estructurado y climatización por bajo-suelo. Precisión de temperatura 22 ± 1 °C con DX-CRAC redundante N+1. Humedad relativa 45–55% con monitoreo continuo. UPS de 40 kVA con autonomía de 4 h + generador diésel para soporte indefinido. Cámaras de seguridad en cada pasillo de rack. Acceso por tarjeta RFID y código PIN por bastidor individual. Extinción limpia HFC-227ea. Monitoreo DCIM en tiempo real con alertas vía SMS/email. Cumple ANSI/TIA-942 nivel Tier II+ para centros de datos. Ideal para almacenamiento de equipos en reparación o de respaldo activo.',
        warehouseType: 'VIP',
        city: 'Medellín',
        address: 'Calle 67 #52-20, Parque Tecnológico Ruta N, Torre Innovación Piso 2',
        postalCode: '050010',
        storageLength: 16,
        storageWidth: 13,
        storageHeight: 4,
        usableArea: 200,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Energía eléctrica estabilizada con UPS dedicado, climatización de precisión, generador propio, Internet fibra 10 Gbps',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: false,
        accessHours: '24/7 con acceso controlado por bastidor',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1000',
        monthlyPrice: 13_200_000,
        capacityOccupied: 30,
    },
    {
        name: 'Depósito Numismática y Coleccionismo — Cali Norte',
        description:
            'Suite de alta seguridad de 95 m² para coleccionistas y casas de subastas que requieren custodia discreta de monedas antiguas, billetes raros, sellos filatélicos, tarjetas deportivas y objetos de colección de alto valor. Temperatura controlada 18–20 °C, HR 45–50%, sin variaciones bruscas. Iluminación actimica direccional con intensidad ajustable. Cámaras 4K con retención 90 días; prohibido el acceso a personal de mantenimiento sin supervisión del titular. Cajas individuales de 20 × 30 × 60 cm disponibles dentro del espacio. Inventario fotográfico de cada pieza al momento del ingreso. Servicio de valuación por experto bajo solicitud (costo adicional). Gestión completamente confidencial: sin publicación de clientes ni inventarios. Seguro de colección hasta USD 250 000 incluido.',
        warehouseType: 'VIP',
        city: 'Cali',
        address: 'Carrera 1N #18-52, Edificio Seguro Premium, Piso B2, Barrio Granada',
        postalCode: '760020',
        storageLength: 10,
        storageWidth: 10,
        storageHeight: 3,
        usableArea: 95,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Energía eléctrica regulada, climatización de precisión, aseo especializado e Internet',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: false,
        accessHours: 'Lun–Vie 9:00 AM – 5:00 PM (solo con cita)',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1601581875039-e899893d520c?q=80&w=1000',
        monthlyPrice: 9_200_000,
        capacityOccupied: 20,
    },

    // ══════════════════════════════════════════════════════════
    //  GENERAL adicionales — Agroalimentario, aeroportuario, etc.
    // ══════════════════════════════════════════════════════════
    {
        name: 'Bodega Aeroportuaria Última Milla — Bogotá El Dorado',
        description:
            'Instalación logística de 580 m² contigua a la zona cargo del Aeropuerto El Dorado, habilitada por la DIAN como depósito temporal para carga aérea nacional e internacional. Ideal para operadores de carga, couriers de último kilómetro y empresas de comercio exterior. Báscula certificada de 500 kg con certificado ONAC. Zona frigorífica portable disponible de 20 m² para carga perecedera en espera. Sistema de etiquetado con código IATA automático. Personal certificado DGR para manejo de mercancía peligrosa clase 3, 5 y 9 según IATA. Tres turnos rotativos de operación 24/7. Acceso con credencial aeroportuaria vigente obligatoria.',
        warehouseType: 'GENERAL',
        city: 'Bogotá',
        address: 'Av. El Dorado #103-15, Zona Cargo El Dorado, Módulo A2',
        postalCode: '110931',
        storageLength: 30,
        storageWidth: 20,
        storageHeight: 6,
        usableArea: 580,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua, energía eléctrica trifásica, Internet fibra 1 Gbps y aseo diario',
        hasSecuritySystem: true,
        hasLoadingDock: true,
        hasParking: true,
        accessHours: '24/7',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8ed7c83a7f?q=80&w=1000',
        monthlyPrice: 9_100_000,
        capacityOccupied: 38,
    },
    {
        name: 'Almacén Alimentos Secos Certificado ICA — Bucaramanga',
        description:
            'Bodega de 690 m² para almacenamiento de alimentos secos no perecederos: granos, harinas, azúcar, aceites envasados, conservas, snacks y bebidas embotelladas. Certificado sanitario INVIMA vigente y concepto favorable ICA. Piso epóxico sanitario lavable con declive hacia sumidero central. Control de plagas mensual con empresa certificada, trampas de monitoreo permanentes. Ventilación natural con ventanas de doble hoja mosquitero. Sin penetraciones de tuberías de aguas negras en el área útil. Mínimo de 15 cm de separación de producto con paredes. Bodeguero disponible en turno diurno para recepción de mercancía. Temperatura ambiente ≤ 28 °C garantizada en época seca. Compatible con BPM (Buenas Prácticas de Manufactura) para industria de alimentos.',
        warehouseType: 'GENERAL',
        city: 'Bucaramanga',
        address: 'Calle 9 #18-40, Parque Empresarial La Flora, Bodega 7',
        postalCode: '680003',
        storageLength: 35,
        storageWidth: 20,
        storageHeight: 7,
        usableArea: 690,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua potable, energía eléctrica, aseo diario y control de plagas mensual incluidos',
        hasSecuritySystem: true,
        hasLoadingDock: true,
        hasParking: true,
        accessHours: 'Lun–Sáb 6:00 AM – 8:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=1000',
        monthlyPrice: 3_700_000,
        capacityOccupied: 52,
    },
    {
        name: 'Almacén Multipropósito con Zonas Modulares — Itagüí MED',
        description:
            'Complejo de 2 000 m² arrendable por módulos de 50 m² desde 1 mes, pensado para PYMES que necesitan crecer sin cambiar de instalación. Actualmente disponibles 8 módulos adyacentes combinables hasta 400 m². Zona administrativa compartida con sala de reuniones de 20 m², baños con vestier y cafetería de empleados. Parqueadero cubierto techado para 25 vehículos. Ciclovía interna señalizada para montacargas hasta 5 t. Rampas niveladoras hidráulicas en andén comunitario. Cada módulo con cerradura inteligente Bluetooth y monitoreo individual. Agua caliente y fría disponible para limpieza. Compatible con industrias no contaminantes: alimentos, textiles, cosméticos, electrodomésticos. No se permiten químicos peligrosos ni almacenamiento de animales vivos.',
        warehouseType: 'GENERAL',
        city: 'Medellín',
        address: 'Calle 65 #55-60, Parque Industrial Sur, Itagüí',
        postalCode: '055400',
        storageLength: 50,
        storageWidth: 40,
        storageHeight: 8,
        usableArea: 2000,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua, energía eléctrica, gas natural, aseo de áreas comunes e Internet compartido',
        hasSecuritySystem: true,
        hasLoadingDock: true,
        hasParking: true,
        accessHours: 'Lun–Sáb 6:00 AM – 10:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1000',
        monthlyPrice: 4_300_000,
        capacityOccupied: 22,
    },
    {
        name: 'Centro Logístico Farmacéutico Seco — Bogotá Kennedy',
        description:
            'Bodega de 420 m² validada para distribución de medicamentos sólidos (tabletas, cápsulas, grageas), OTC y productos para el hogar de uso médico que no requieren cadena de frío. Temperatura ambiente entre 15 °C y 25 °C controlada mediante HVAC central. Humedad relativa < 60%. Área de cuarentena separada con acceso restringido solo a personal de QA. Área de devoluciones identificada y separada del stock apto. Registro de access log por operario. Validación de instalaciones IQ/OQ conforme a INVIMA. Sin acceso a personal sin tiquete de operación. Sistema de picking por FIFO garantizado. No se admiten productos que requieran 2–8 °C ni medicamentos de control especial.',
        warehouseType: 'DELICADOS',
        city: 'Bogotá',
        address: 'Calle 38 Sur #79B-22, Parque Empresarial Kennedy Norte',
        postalCode: '111611',
        storageLength: 26,
        storageWidth: 16,
        storageHeight: 4,
        usableArea: 420,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua, energía eléctrica, HVAC, Internet 500 Mbps y aseo diario certificado',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: true,
        accessHours: 'Lun–Vie 7:00 AM – 8:00 PM / Sáb 8:00 AM – 1:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=1000',
        monthlyPrice: 7_200_000,
        capacityOccupied: 48,
    },
    {
        name: 'Almacén Carga Peligrosa Clase 1 — Buenaventura Puerto',
        description:
            'Polvorín y almacén de carga peligrosa clase 1 (explosivos) y clase 4 (sólidos/líquidos inflamables) habilitado por la Superintendencia de Puertos y el Industria Militar. Ubicado en el recinto portuario de Buenaventura, permite el almacenamiento previo a la consignación al buque. Construcción con muros RF-240 (4 h resistencia al fuego). Distancias de seguridad reglamentarias a otras instalaciones (>150 m). Sistemas de supresión de explosiones con paneles de alivio de presión. Monitoreo por personal especializado en DG las 24 h. Sin acceso a personal civil sin permiso del Ministerio de Defensa. Solo para cargamentos con número UN y ficha de emergencia ERI en regla.',
        warehouseType: 'QUIMICA',
        city: 'Buenaventura',
        address: 'Zona Franca Portuaria Buenaventura, Lote EXPL-2',
        postalCode: '764530',
        storageLength: 25,
        storageWidth: 15,
        storageHeight: 5,
        usableArea: 375,
        utilitiesIncluded: false,
        utilitiesResponsible: 'ARRENDATARIO',
        utilitiesDetails: 'Energía antiexplosión y agua a cargo del arrendatario; iluminación de emergencia incluida',
        hasSecuritySystem: true,
        hasLoadingDock: true,
        hasParking: false,
        accessHours: 'Uso con escolta autorizada Lun–Vie 7:00 AM – 5:00 PM',
        isAvailable: false,
        imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1000',
        monthlyPrice: 8_900_000,
        capacityOccupied: 15,
    },
    {
        name: 'Cámara Maduración y Cadena Frío Tropical — Barranquilla',
        description:
            'Cámara de maduración controlada de 300 m² para frutas tropicales de exportación (banano, mango Tommy, aguacate Hass, piña MD2) que requieren maduración en destino a temperatura y concentración de etileno supervisadas. Temperatura ajustable entre 12 °C y 20 °C según estadio. Inyección de etileno calibrada (100–200 ppm) mediante cicladores automáticos. Circulación de aire forzada homogénea para maduración uniforme. Certificación GlobalGAP y TESCO NURTURE para exportación a Europa. Pallets europeos EPAL disponibles en préstamo. Personal especialista en poscosecha disponible bajo solicitud. No se mezclan frutas de diferentes clientess en el mismo ciclo de maduración.',
        warehouseType: 'REFRIGERADA',
        city: 'Barranquilla',
        address: 'Km 5 Circunvalar Norte, Parque Agroindustrial La Loma, Bodega 3',
        postalCode: '080001',
        storageLength: 20,
        storageWidth: 15,
        storageHeight: 5,
        usableArea: 300,
        utilitiesIncluded: false,
        utilitiesResponsible: 'COMPARTIDO',
        utilitiesDetails: 'Submedidor de energía para refrigeración; agua, etileno e Internet incluidos en el canon',
        hasSecuritySystem: true,
        hasLoadingDock: true,
        hasParking: true,
        accessHours: 'Lun–Sáb 5:00 AM – 10:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=1000',
        monthlyPrice: 5_800_000,
        capacityOccupied: 65,
    },
    {
        name: 'Patio Logístico Vehículos Ligeros — Bogotá Autopista Norte',
        description:
            'Parqueadero logístico de 1 000 m² techado con policarbonato traslúcido, destinado al almacenamiento y custodia de automóviles particulares, furgonetas de carga liviana y motos de reparto. Acceso por portón automático con lector de placa LPR. Control de 50 vehículos simultáneos. CCTV 360° con IA de detección de golpes o manipulaciones. Seguro de responsabilidad civil incluido hasta COP 50 M por vehículo. Personal de parqueo 24 h. Zona de pre-alistamiento de 200 m² para engrase, limpieza exterior y verificación de estado. No incluye reparaciones mecánicas ni trabajos eléctricos dentro del parqueadero. Ideal para concesionarios, empresas de rent-a-car y flotas de última milla.',
        warehouseType: 'EXTERIOR',
        city: 'Bogotá',
        address: 'Autopista Norte Km 8 #158-32, Parque Industrial Norkín',
        postalCode: '110111',
        storageLength: 50,
        storageWidth: 20,
        storageHeight: 4,
        usableArea: 1000,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Energía eléctrica, agua y aseo diario incluidos; Internet para cámaras y lector LPR',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: true,
        accessHours: '24/7',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1581094271901-8022df4466f9?q=80&w=1000',
        monthlyPrice: 4_000_000,
        capacityOccupied: 30,
    },
    {
        name: 'Suite Logística Cosméticos y Perfumería — Bogotá Chapinero',
        description:
            'Espacio de 190 m² especializado en el almacenamiento de cosméticos, fragancias de lujo, dermocosméticos y productos de cuidado personal. Temperatura 18–22 °C con HR < 55% para conservar la integridad de emulsiones, aceites esenciales y fórmulas coloreadas. Iluminación LED de espectro cálido que no altera la apreciación visual de los productos. Estanterías de PVC sanitario con separación por marca. Área de preembalaje de 30 m² con mesa de trabajo y selladora de bolsas incluida. Certificado Registro Sanitario INVIMA para distribución de cosméticos. Control de olores: ventilación forzada que evita la migración de aromas entre clientes. Sin acceso a productos alimenticios ni farmacéuticos en el mismo espacio.',
        warehouseType: 'DELICADOS',
        city: 'Bogotá',
        address: 'Carrera 13 #57-42, Edificio Corporate Park, Piso 1, Chapinero',
        postalCode: '110221',
        storageLength: 19,
        storageWidth: 10,
        storageHeight: 4,
        usableArea: 190,
        utilitiesIncluded: true,
        utilitiesResponsible: 'ARRENDADOR',
        utilitiesDetails: 'Agua, energía eléctrica, ventilación forzada, HVAC, Internet 300 Mbps y aseo',
        hasSecuritySystem: true,
        hasLoadingDock: false,
        hasParking: false,
        accessHours: 'Lun–Vie 7:00 AM – 7:00 PM / Sáb 8:00 AM – 2:00 PM',
        isAvailable: true,
        imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8ed7c83a7f?q=80&w=1000',
        monthlyPrice: 4_700_000,
        capacityOccupied: 40,
    },
];

const seedWarehouses = async () => {
    try {
        console.log('⏳ Conectando a la base de datos...');
        await sequelize.authenticate();
        console.log('✅ Conexión exitosa.\n');

        console.log(`🏗️  Iniciando seeder de ${warehouses.length} bodegas...\n`);

        let created = 0;
        let skipped = 0;

        for (const data of warehouses) {
            const [, wasCreated] = await Warehouse.findOrCreate({
                where: { name: data.name },
                defaults: data as any,
            });

            if (wasCreated) {
                console.log(`  ✅ [NUEVA]    ${data.name} (${data.city} · ${data.warehouseType})`);
                created++;
            } else {
                console.log(`  ⏭️  [OMITIDA]  ${data.name} (ya existe)`);
                skipped++;
            }
        }

        console.log('\n────────────────────────────────────────────────');
        console.log(`✅ Bodegas nuevas creadas : ${created}`);
        console.log(`⏭️  Bodegas omitidas      : ${skipped}`);
        console.log(`📦 Total procesadas       : ${warehouses.length}`);
        console.log('🎉 ¡Seeder de bodegas finalizado con éxito!');

        process.exit(0);
    } catch (error) {
        console.error('❌ Error en el seeder de bodegas:', error);
        process.exit(1);
    }
};

seedWarehouses();
