name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 3.137.149.26
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd LogiStock-Solutions
            git fetch origin main
            git reset --hard origin/main
            npm install
            npm run build
            pm2 restart logistock
